import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import QueryProvider from "@/components/providers/query-provider";
import NotistackProvider from "@/components/providers/snackbar-provider";
import CartProviderWrapper from "@/components/providers/cart-provider";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} text-text antialiased`}>
        <NextTopLoader showSpinner={false} color="#c85387" />
        <QueryProvider>
          <CartProviderWrapper>
            <NotistackProvider>
              <Header />
              {children}
              <Footer />
            </NotistackProvider>
          </CartProviderWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
